Fix plotting of values containers in an array
Before this commit, attempting to plot a value in an array would
trigger the following exception:

Traceback (most recent call last):
  File "/opt/ros/eloquent/lib/python3.6/site-packages/rqt_plot/plot_widget.py", line 259, in on_topic_edit_textChanged
    plottable, message = is_plottable(self._node, topic_name)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/rqt_plot/plot_widget.py", line 154, in is_plottable
    fields, message = get_plot_fields(node, topic_name)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/rqt_plot/plot_widget.py", line 137, in get_plot_fields
    for slot, slot_type in field_class.get_fields_and_field_types().items():
AttributeError: 'NoneType' object has no attribute 'get_fields_and_field_types'

Line 129 in plot_widget.py:

    field_class = message_helpers.get_message_class(slot_type)

...would be executed with slot_type set to 'sequence<foo_msgs/Foo>' which
returns a None value. field_class is set to None and the call to
get_fields_and_field_types is then failing.

This pull request adds an extra layer of logic before calling get_message_class
to ensure that, if the type is an array, we extract the inner array type
instead of attempting to run get_message_class on the DDS sequence type
directly.

Signed-off-by: Thomas Moulard <tmoulard@amazon.com>