Fix #35 - "bottom cannot be >= top" matplotlib error (#52)
* Fix #35 - "bottom cannot be >= top" matplotlib error

Matplotlib emits errors like the following under specific canvas
layouts:

```console
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_plot/data_plot/mat_data_plot.py", line 107, in resizeEvent
    self.figure.tight_layout()
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1756, in tight_layout
    self.subplots_adjust(**kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1612, in subplots_adjust
    self.subplotpars.update(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 230, in update
    raise ValueError('bottom cannot be >= top')
ValueError: bottom cannot be >= top
```

Current patch catches and suppresses that exception.

References:
- https://github.com/matplotlib/matplotlib/pull/10915
- https://github.com/ros-visualization/rqt_plot/issues/35

* renamed to `safe_tight_layout`, inverted logic to avoid duplicating the call

Co-authored-by: Dirk Thomas <dirk-thomas@users.noreply.github.com>